#!/usr/bin/env bash
alias powerline-config="$ZTVPDIR/powerline/scripts/powerline-config --config-path $ZTVPDIR/powerline-config"
alias powerline-render="$ZTVPDIR/powerline/scripts/powerline-config --config-path $ZTVPDIR/powerline-config"

function goat {
    echo $GOAT
}

function cls {
  clear
  if command -v toilet >/dev/null 2>&1; then
    #toilet -w `tput cols` "$HOST"
    goat
  else
    echo "Welcome to $HOST."
  fi
}

function aws-profile {
  env $(ruby -e 'require "inifile"; print IniFile.load("#{ENV["HOME"]}/.aws/credentials")["'$1'"].map { |k, v| "#{k.upcase}=#{v}" }.join(" ")') ${@:2}
}

alias ls='ls -lhFAH --color=force'
alias map='xargs -L1'
alias tweet='t update'
alias tweets='t timeline | less'
alias fucking=sudo
alias dc=popd
alias lls='ls | less'

if [[ "$PLATFORM" -eq "Darwin" ]]
then
  function setjdk() {
    if [ $# -ne 0 ]; then
       removeFromPath '/System/Library/Frameworks/JavaVM.framework/Home/bin'
       if [ -n "${JAVA_HOME+x}" ]; then
         removeFromPath $JAVA_HOME
       fi
       export JAVA_HOME=`/usr/libexec/java_home -v $@`
       export PATH=$JAVA_HOME/bin:$PATH
     fi
   }
   function removeFromPath() {
     export PATH=$(echo $PATH | sed -E -e "s;:$1;;" -e "s;$1:?;;")
   }
fi

function awsp() {
  if [[ "$1" == "production" ]]
    then RPROMPT=''
    else RPROMPT=''
  fi
  export AWS_DEFAULT_PROFILE=$1
}

alias fuck='$(thefuck $(fc -ln -1))'

