#!/usr/bin/env bash
alias powerline-config="$ZTVPDIR/powerline/scripts/powerline-config --config-path $ZTVPDIR/powerline-config"
alias powerline-render="$ZTVPDIR/powerline/scripts/powerline-config --config-path $ZTVPDIR/powerline-config"

function vpn {
  /usr/bin/env osascript <<-EOF
    tell application "System Events"
      tell current location of network preferences
        set VPN to service "Localytics $1 VPN"
        if exists VPN then
          if current configuration of VPN is not connected then
            log "Connecting to $1..."
            connect VPN
            repeat while (current configuration of VPN is not connected)
              delay 1
            end repeat
            log "Connected."
          else
            log "Disconnecting from $1..."
            disconnect VPN
            repeat while (current configuration of VPN is connected)
              delay 1
            end repeat
            log "Disconnected."
          end if
        end if
      end tell
    end tell
EOF
}

function goat {
    echo $GOAT
}

function cls {
  clear
  if command -v toilet >/dev/null 2>&1; then
    #toilet -w `tput cols` "$HOST"
    goat
  else
    echo "Welcome to $HOST."
  fi
}

function in {
  pushd $1 > /dev/null && {
    sh -c ${@:2}
    popd > /dev/null
  }
}

function aws-profile {
  env $(ruby -e 'require "inifile"; print IniFile.load("#{ENV["HOME"]}/.aws/credentials")["'$1'"].map { |k, v| "#{k.upcase}=#{v}" }.join(" ")') ${@:2}
}

alias ls='ls -lhFAH --color=force'
alias map='xargs -L1'
alias tweet='t update'
alias tweets='t timeline | less'
alias fucking=sudo
alias dc=popd
alias lls='ls | less'

if [[ "$PLATFORM" -eq "Darwin" ]]
then
  function setjdk() {
    if [ $# -ne 0 ]; then
       removeFromPath '/System/Library/Frameworks/JavaVM.framework/Home/bin'
       if [ -n "${JAVA_HOME+x}" ]; then
         removeFromPath $JAVA_HOME
       fi
       export JAVA_HOME=`/usr/libexec/java_home -v $@`
       export PATH=$JAVA_HOME/bin:$PATH
     fi
   }
   function removeFromPath() {
     export PATH=$(echo $PATH | sed -E -e "s;:$1;;" -e "s;$1:?;;")
   }
fi

function st() {
  osascript -e "tell application \"SourceTree\"" -e "open \"$(realpath $1)\"" -e "activate" -e "end tell"
}

function google() {
  osascript \
    -e "tell application \"Google Chrome\"" \
      -e "tell (make new window)" \
        -e "set URL of active tab to \"http://google.com/search?q=$(urlencode "$1")\"" \
      -e "end tell" \
      -e "activate" \
    -e "end tell"
}

function awsp() {
  if [[ "$1" == "production" ]]
    then RPROMPT=''
    else RPROMPT=''
  fi
  export AWS_DEFAULT_PROFILE=$1
}

