---
- hosts: all
  tasks:
    - name: dotfiles rc
      copy: content="{{playbook_dir}}" dest="{{ansible_env.HOME}}/.dotfilesdir"

    - name: link dotfiles
      with_items:
        - vimrc
        - vim
        - zshrc
        - zsh
        - tmux.conf
        - tmux
        - bin
        - gitconfig
        - gitignore_global
        - hgrc
        - hgignore_global
      file: src="{{playbook_dir}}/{{item}}" dest="{{ansible_env.HOME}}/.{{item}}" state=link force=yes

    - name: install packages
      with_items:
        - binutils
        - coreutils
        - autogen
        - autoconf
        - automake
        - awscli
        - jq
        - rbenv
        - thefuck
        - ctags
        - htop
        - zsh
        - vim
      homebrew: name="{{item}}" state=present

    - name: ruby install
      shell: zsh -c 'rbenv install -s 2.3.0 && rbenv global 2.3.0'

    - name: vundle install
      shell: vim +VundleInstall +qall

    - name: tpm install
      shell: "{{playbook_dir}}/tmux/tpm/bin/install_plugins"

